profile=developer
logging.level.com.example.demo.controllers=trace

#variables:
notes.max-pages.size=100
users.max-pages.size=100
# logging filter stop
logging.filter=false
logging.interceptor=false
# spring security details:
spring.security.user.name=zero
spring.security.user.password=zerobear