spring.application.name=Personal-Knowledge-Management-Platform
# DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/PersonalNotesManagment
spring.datasource.username=root
spring.datasource.password=zerobear
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#acturators :
management.endpoints.web.exposure.include=*
#conditional properties :
#ai.agent.service=claude
#profiles:
#profile="main"
spring.profiles.active=dev

